spring.application.name=ProductsManagementSystom

spring.datasource.url=jdbc:postgresql://localhost:5432/csv
spring.datasource.username=postgres
spring.datasource.password=shubham@20
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000
app.jwt.cookie-name=jwt-token