spring.application.name=ProductsManagementSystom

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-cool-block-atydsn8b.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_hQoR9X2Fgrlt}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000
app.jwt.cookie-name=jwt-token
app.jwt.cookie-secure=${JWT_COOKIE_SECURE:false}
app.jwt.cookie-same-site=${JWT_COOKIE_SAME_SITE:Lax}

# CORS Configuration
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://productmanagementsystem-eight.vercel.app,http://localhost:4200}